[project]
name = "sc-be-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "av>=14.4.0",
  "bluezero>=0.9.1",
  "fastapi>=0.115.13",
  "ffmpeg-python>=0.2.0",
  "jupyter>=1.1.1",
  "keyboard>=0.13.5",
  "matplotlib>=3.10.3",
  "numpy<2.0",
  "opencv-stubs>=0.0.11",
  "picamera2>=0.3.27",
  "pytest>=8.4.1",
  "setproctitle>=1.3.6",
  "ultralytics>=8.3.158",
  "uvicorn>=0.35.0",
]
[dependency-groups]
dev = [
    "opencv-stubs>=0.0.11",
    "ruff>=0.11.12",
]
