[device]
enabled = true
name = "sst-cam"
model = "sst-cam-v2"
version = "1.0.0"
serial_number = "00000001"
manufacturer = "Scout Sport Technology"
timezone = "UTC"
timestamp = 'monotonic'
[device.network]
enabled = true
[device.network.wiFi]
enabled = true
wifi_type = "station"
[device.network.wiFi.station]
wifi_ssid = "your_wifi_ssid"
wifi_password = "your_wifi_password"
[device.network.wiFi.station.static_ip]
enabled = false
ip_address = "192.168.1.100"
subnet_mask = "255.255.255.0"
gateway = "192.168.1.1"
[device.network.wiFi.access_point]
ssid = "your_ap_ssid"
password = "your_ap_password"
[device.network.ethernet]
ethernet_enabled = true
[device.network.ethernet.static_ip]
enabled = false
ip_address = "192.168.1.100"
subnet_mask = "255.255.255.0"
gateway = "192.168.1.1"
[device.bluetooth]
enabled = false
name = "sst-cam"
password = "0000"
